[versions]
indra = "3.1.3"

cloud = "2.0.0-beta.1"

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }

[libraries]
cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud" }
