matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences
            - pymdownx.tabbed
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - "docs/**/*.md"
    default_encoding: utf-8
